# Makes all the kernels

MAKE=make

.PHONY: all
all:
	cd lkf && $(MAKE)
#	cd tableaux && $(MAKE)
#	cd modal && $(MAKE)

.PHONY: clean
clean:
	cd lkf && $(MAKE) clean
#	cd tableaux && $(MAKE) clean
#	cd modal && $(MAKE) clean

