# Makes all the calculi

MAKE=make

.PHONY: all
all:
	cd modal && $(MAKE)
	# no module but only a sig file
	#cd nested-sequents && $(MAKE)

.PHONY: clean
clean:
	cd modal && $(MAKE) clean
	#cd nested-sequents && $(MAKE) clean

