# Makes all the kernels

MAKE=make

.PHONY: all
all:
	cd lkf && $(MAKE)
	cd ljf && $(MAKE)
	cd imbed && $(MAKE)

.PHONY: clean
clean:
	cd lkf && $(MAKE) clean
	cd ljf && $(MAKE) clean
	cd imbed && $(MAKE) clean

