# Makes all the resolution fpcs

MAKE=make

.PHONY: all
all:
	cd resolution && $(MAKE)
	cd tableaux && $(MAKE)
	cd modal && $(MAKE)

.PHONY: clean
clean:
	cd resolution && $(MAKE) clean
	cd tableaux && $(MAKE) clean
	cd modal && $(MAKE) clean

