# Makefile for the imbedding
SRCS=$(wildcard *.mod)
OBJS=$(SRCS:.mod=.lp)
#VPATH = ../common

#export TJPATH = ../common

.PHONY: all
all: compile

compile: $(OBJS)

cc: all clean

%.lpo : %.mod %.sig
	tjcc  $*

%.lp : %.lpo
	tjlink  $*

-include depend
depend: *.mod *.sig
		tjdepend *.mod  > depend-stage
		mv depend-stage depend

.PHONY: clean
clean:
	rm -f *.lpo *.lp *.dt depend

untrace:
	rm *.dt
