sig os-lmfstar.

accum_sig certificatesOS.
accum_sig certificatesLMFStar.
accum_sig lists.
accum_sig base.

% for the accessibility relation, we use the same 'rel' in all problems
type rel A -> A -> atm.

% fixed index for relations, should be improved!
type relind index.

% The certificate for the translation is polymorphic but keep trace of which branch we are in: modal one
% or the one generated by the translation from fol
kind phase, ophase type.
type boxphase, normalphase ophase.

% osphase is used when we apply a modal rule: one phase for the box, one for the diamonds
% list index is the possible list of diamonds we need to keep track of
% the two atoms are current and next labels
type oscert cert -> osphase -> list index -> label -> label -> cert.
